[package]
name = "riscy-rust"
version = "0.1.0"
edition = "2021"

[dependencies.bits]
path = "lib/bits"

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
enum_dispatch = "0.3.11"
modular-bitfield = "0.11.2"
num = "0.4.0"
strum = { version = "0.25.0", features = ["derive"] }
